In [93]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_profiling
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor

In [2]:
df_detail = pd.read_csv("CB Horizon Daily Detail Data 2018.csv")

In [3]:
df_detail.head(2)

,Arrival Time,Check In Date,Completion Date,Customer Facing Flag,Customer Key,DCV Ind,DTV Ind,Director,Drive Time Points,Dwelling Type,...,Supervisor,Survey Response Value,Technician,Truck Roll Ind,Verified Vendor,Work Order Category,Work Order Class,Work Order Number,Work Order Type,Zip Code
0,6/18/2018 10:52:00 AM,6/18/2018 11:17:00 AM,6/18/2018 11:16:00 AM,Y,71479796,0,0,OPEN,2,MDU,...,Brian Ginley,NaN,STEVE HEUSER,1,N,SRO,D,7219822,Sro,44147
1,5/16/2018 2:46:00 PM,6/5/2018 2:46:00 PM,5/16/2018 2:46:00 PM,Y,106221992,0,0,NaN,2,MDU,...,NaN,NaN,S SHORE UNDERGOUNDS 70546,1,N,SRO,C,7266786,Sro,44116

In [4]:
df_detail['Arrival Time'] = pd.to_datetime(df_detail['Arrival Time'], errors = 'coerce')
df_detail['Check In Date'] = pd.to_datetime(df_detail['Check In Date'], errors = 'coerce')
#df_detail['Completion Date'] = pd.to_datetime(df_detail['Completion Date'], errors = 'coerce')

In [5]:
# df_detail['New Time'] = df_detail['Completion Date'].astype(np.int64) - \
#     df_detail[['Arrival Time','Check In Date']].min(axis=1).astype(np.int64)

# df_detail['New Time'] = df_detail[['Arrival Time','Check In Date']].min(axis=1)

df_detail['New Time'] = (df_detail['Check In Date'] - df_detail['Arrival Time']).dt.total_seconds() / 60

In [6]:
df_detail.head(2)

,Arrival Time,Check In Date,Completion Date,Customer Facing Flag,Customer Key,DCV Ind,DTV Ind,Director,Drive Time Points,Dwelling Type,...,Survey Response Value,Technician,Truck Roll Ind,Verified Vendor,Work Order Category,Work Order Class,Work Order Number,Work Order Type,Zip Code,New Time
0,2018-06-18 10:52:00,2018-06-18 11:17:00,6/18/2018 11:16:00 AM,Y,71479796,0,0,OPEN,2,MDU,...,NaN,STEVE HEUSER,1,N,SRO,D,7219822,Sro,44147,25.0
1,2018-05-16 14:46:00,2018-06-05 14:46:00,5/16/2018 2:46:00 PM,Y,106221992,0,0,NaN,2,MDU,...,NaN,S SHORE UNDERGOUNDS 70546,1,N,SRO,C,7266786,Sro,44116,28800.0

In [7]:
df_detail['New Time'].describe()

count    3.310280e+05
mean     6.558931e+04
std      5.809331e+06
min     -1.536913e+08
25%      2.100000e+01
50%      1.200000e+02
75%      4.220000e+02
max      1.534722e+08
Name: New Time, dtype: float64

In [49]:
df_subset = df_detail.drop(columns=['Arrival Time','Check In Date','Completion Date'])
df_subset = df_subset.drop(columns=['Customer Key','Director','Employee Type Group','Entered By Employee Typ Group'])
df_subset = df_subset.drop(columns=['Entered By Employee Type Code','Entered By Employee Type Desc','Entered By Labor Type','Entered By Name','Technician'])
df_subset = df_subset.drop(columns=['Entered Date','FSI Ind','Field Tech Ind','Installer ID','Manager'])
df_subset = df_subset.drop(columns=['Number of Records','Site Code','Supervisor'])
df_subset = df_subset.drop(columns=['Work Order Category','Job Code Desc','Work Order Number'])
df_subset = df_subset.drop(columns=['Entered By Site','NPS Status','Service Call Product'])
df_subset = df_subset.drop(columns=['Repeat Solution Code - Ops','Repeat Solution Code - iDrive','Repeat Solution Desc - Ops','Repeat Solution Desc - iDrive','Repeat Solution Functional Group - Ops','Repeat Solution Group - Ops','Repeat Solution Group - iDrive','Repeat Work Order Entered Date - Ops','Repeat Work Order Number - Ops','Repeat Work Order Number - iDrive','Solution Code','Solution Desc','Solution Functional Group','Solution Group'])
df_subset = df_subset.drop(columns=['Fidning Code','Filtered Finding Ind','Filtered Solution Ind','Finding Desc'])
df_subset = df_subset.drop(columns=['Finding Functional Group','Finding Group'])
df_subset = df_subset.drop(columns=['Sub System','Zip Code','Node'])
df_subset = df_subset.drop(columns=['Repeat DCV Ind - Ops',
'Repeat DTV Ind - Ops',
'Repeat Filtered Finding Ind - Ops',
'Repeat Filtered Finding Ind - iDrive',
'Repeat Filtered Solution Ind - Ops',
'Repeat Finding Code - Ops',
'Repeat Finding Code - iDrive',
'Repeat Finding Desc - Ops',
'Repeat Finding Desc - iDrive',
'Repeat Finding Functional Group - Ops',
'Repeat Finding Group - Ops',
'Repeat Finding Group - iDrive',
'Repeat Interval - Ops',
'Repeat Interval - iDrive',
'Repeat Points',
'Repeat Service Call Product - Ops'])
df_subset = df_subset.drop(columns=['QC Chargeback Amount','QC Chargeback Eligibility','QC Inspection Opportunities','QC Inspection Passes','QC Remote Inspection','QC iDrive Eligibility'])
df_subset = df_subset.drop(columns=['Repeat Filtered Solution Ind - iDrive','Repeat Flag - iDrive','Office Only Flag Key'])

In [50]:
df_subset2 = df_subset[df_subset['New Time'].notnull()]
#df_subset2 = df_subset2[df_subset2['New Time'] > 1]  
#df_subset2 = df_subset2[df_subset2 < 400]  

indexNames = df_subset2[ df_subset2['New Time'] < 1 ].index
df_subset2.drop(indexNames , inplace=True)

indexNames = df_subset2[ df_subset2['New Time'] > 400 ].index
df_subset2.drop(indexNames , inplace=True)

/Users/rsimon/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [60]:
df_survey_subset = df_subset2[df_subset2['Survey Response Value'].notnull()]
df_nosurvey_subset = df_subset2[df_subset2['Survey Response Value'].isnull()]

In [71]:
#df_survey_subset.describe()

In [72]:
#df_nosurvey_subset.drop(columns=['Survey Response Value'] , inplace=True)
#df_nosurvey_subset.describe()

In [70]:
#pandas_profiling.ProfileReport(df_nosurvey_subset)

In [64]:
nosurvey_drivetimepoints = df_nosurvey_subset['Drive Time Points']

In [65]:
nosurvey_points = df_nosurvey_subset['Points']

In [66]:
nosurvey_y = df_nosurvey_subset['New Time']

In [104]:
# Calculate the absolute errors
errors = abs(nosurvey_points*5 - nosurvey_y)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'minutes.')

Mean Absolute Error: 95.89 minutes.

In [67]:
nosurvey_X = df_nosurvey_subset.drop(columns=['Drive Time Points','Points','New Time'])

In [78]:
nosurvey_X = sm.add_constant(nosurvey_X)
dum_ns_X = pd.get_dummies(nosurvey_X)

In [79]:
dum_ns_X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 189835 entries, 0 to 367573
Data columns (total 85 columns):
const                                 189835 non-null float64
DCV Ind                               189835 non-null int64
DTV Ind                               189835 non-null int64
HC Equipment Passed                   189835 non-null int64
HC Equipment                          189835 non-null int64
Service Call Ind                      189835 non-null int64
Truck Roll Ind                        189835 non-null int64
Customer Facing Flag_N                189835 non-null uint8
Customer Facing Flag_Y                189835 non-null uint8
Dwelling Type_MDU                     189835 non-null uint8
Dwelling Type_Non-Residential         189835 non-null uint8
Dwelling Type_SFU                     189835 non-null uint8
Employee Type Code_5I                 189835 non-null uint8
Employee Type Code_H3                 189835 non-null uint8
Employee Type Code_H5                 189835 non-null uint8
Job Type_Diagnostic Customer Visit    189835 non-null uint8
Job Type_Diagnostic Tap Visit         189835 non-null uint8
Job Type_Disconnect                   189835 non-null uint8
Job Type_Install                      189835 non-null uint8
Job Type_SRO                          189835 non-null uint8
Job Type_Trouble Call                 189835 non-null uint8
Labor Type_Contractor                 189835 non-null uint8
Labor Type_In House                   189835 non-null uint8
Q Code_%                              189835 non-null uint8
Q Code_&                              189835 non-null uint8
Q Code_0                              189835 non-null uint8
Q Code_1                              189835 non-null uint8
Q Code_3                              189835 non-null uint8
Q Code_5                              189835 non-null uint8
Q Code_?                              189835 non-null uint8
Q Code_A                              189835 non-null uint8
Q Code_G                              189835 non-null uint8
Q Code_I                              189835 non-null uint8
Q Code_K                              189835 non-null uint8
Q Code_L                              189835 non-null uint8
Q Code_Q                              189835 non-null uint8
Q Code_R                              189835 non-null uint8
Q Code_S                              189835 non-null uint8
Q Code_V                              189835 non-null uint8
Q Code_W                              189835 non-null uint8
Q Code_X                              189835 non-null uint8
Q Code_Y                              189835 non-null uint8
Q Code_Z                              189835 non-null uint8
Region_California                     189835 non-null uint8
Region_Central Region                 189835 non-null uint8
Region_Northeast Region               189835 non-null uint8
Region_Southeast Region               189835 non-null uint8
Region_Southwest Region               189835 non-null uint8
Region_Virginia                       189835 non-null uint8
Site_Cleveland                        189835 non-null uint8
Site_Connecticut                      189835 non-null uint8
Site_Gainesville/Ocala                189835 non-null uint8
Site_Greater Louisiana                189835 non-null uint8
Site_Hampton Roads                    189835 non-null uint8
Site_Kansas/NW Arkansas               189835 non-null uint8
Site_Las Vegas                        189835 non-null uint8
Site_Macon                            189835 non-null uint8
Site_New Orleans                      189835 non-null uint8
Site_Northern Virginia                189835 non-null uint8
Site_Oklahoma City                    189835 non-null uint8
Site_Omaha/Sun Valley                 189835 non-null uint8
Site_Orange County                    189835 non-null uint8
Site_Palos Verdes                     189835 non-null uint8
Site_Pensacola                        189835 non-null uint8
Site_Phoenix                          189835 non-null uint8
Site_Rhode Island                     189835 non-null uint8
Site_Roanoke                          189835 non-null uint8
Site_San Diego                        189835 non-null uint8
Site_Santa Barbara                    189835 non-null uint8
Site_Tulsa                            189835 non-null uint8
Verified Vendor_N                     189835 non-null uint8
Verified Vendor_Y                     189835 non-null uint8
Work Order Class_*                    189835 non-null uint8
Work Order Class_C                    189835 non-null uint8
Work Order Class_D                    189835 non-null uint8
Work Order Class_H                    189835 non-null uint8
Work Order Class_S                    189835 non-null uint8
Work Order Class_T                    189835 non-null uint8
Work Order Type_Disconnect            189835 non-null uint8
Work Order Type_Downgrade             189835 non-null uint8
Work Order Type_Install               189835 non-null uint8
Work Order Type_Restart               189835 non-null uint8
Work Order Type_Sro                   189835 non-null uint8
Work Order Type_Trouble Call          189835 non-null uint8
Work Order Type_Upgrade               189835 non-null uint8
dtypes: float64(1), int64(6), uint8(78)
memory usage: 25.7 MB

In [90]:
X_train, X_test, y_train, y_test = train_test_split(dum_ns_X, nosurvey_y, test_size = 0.2, random_state = 0)

In [84]:
model=sm.OLS(y_train, X_train)
model = model.fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               New Time   R-squared:                       0.553
Model:                            OLS   Adj. R-squared:                  0.553
Method:                 Least Squares   F-statistic:                     3034.
Date:                Fri, 09 Aug 2019   Prob (F-statistic):               0.00
Time:                        14:24:40   Log-Likelihood:            -8.6961e+05
No. Observations:              151868   AIC:                         1.739e+06
Df Residuals:                  151805   BIC:                         1.740e+06
Df Model:                          62
Covariance Type:            nonrobust
======================================================================================================
                                         coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
const                              -6.522e+11   1.95e+12     -0.334      0.739   -4.48e+12    3.18e+12
DCV Ind                            -2.005e+12   5.73e+12     -0.350      0.726   -1.32e+13    9.22e+12
DTV Ind                            -1.684e+12   6.96e+12     -0.242      0.809   -1.53e+13     1.2e+13
HC Equipment Passed                   -0.4017      0.899     -0.447      0.655      -2.164       1.361
HC Equipment                           4.9463      0.871      5.679      0.000       3.239       6.654
Service Call Ind                    7.628e+12   1.21e+13      0.633      0.527    -1.6e+13    3.13e+13
Truck Roll Ind                        59.6142      1.029     57.921      0.000      57.597      61.631
Customer Facing Flag_N              9.804e+11   2.15e+13      0.046      0.964   -4.12e+13    4.31e+13
Customer Facing Flag_Y              9.804e+11   2.15e+13      0.046      0.964   -4.12e+13    4.31e+13
Dwelling Type_MDU                  -3.815e+11   3.88e+12     -0.098      0.922   -7.98e+12    7.22e+12
Dwelling Type_Non-Residential      -3.815e+11   3.88e+12     -0.098      0.922   -7.98e+12    7.22e+12
Dwelling Type_SFU                  -3.815e+11   3.88e+12     -0.098      0.922   -7.98e+12    7.22e+12
Employee Type Code_5I              -9.448e+10   1.13e+13     -0.008      0.993   -2.22e+13     2.2e+13
Employee Type Code_H3               1.411e+11   3.54e+13      0.004      0.997   -6.92e+13    6.95e+13
Employee Type Code_H5              -9.448e+10   1.13e+13     -0.008      0.993   -2.22e+13     2.2e+13
Job Type_Diagnostic Customer Visit -4.289e+11   5.57e+12     -0.077      0.939   -1.13e+13    1.05e+13
Job Type_Diagnostic Tap Visit      -7.504e+11   6.11e+12     -0.123      0.902   -1.27e+13    1.12e+13
Job Type_Disconnect                 7.567e+11   2.17e+12      0.348      0.728    -3.5e+12    5.02e+12
Job Type_Install                    1.266e+12   3.31e+12      0.383      0.702   -5.22e+12    7.75e+12
Job Type_SRO                        6.859e+11   3.29e+12      0.208      0.835   -5.77e+12    7.14e+12
Job Type_Trouble Call              -2.434e+12   3.46e+12     -0.704      0.481   -9.21e+12    4.34e+12
Labor Type_Contractor              -6.509e+11   1.29e+13     -0.051      0.960   -2.59e+13    2.46e+13
Labor Type_In House                -4.153e+11   1.21e+13     -0.034      0.973   -2.41e+13    2.33e+13
Q Code_%                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_&                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_0                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_1                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_3                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_5                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_?                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_A                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_G                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_I                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_K                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_L                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_Q                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_R                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_S                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_V                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_W                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_X                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_Y                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Q Code_Z                           -5.372e+10   3.72e+11     -0.145      0.885   -7.82e+11    6.75e+11
Region_California                  -2.209e+11   2.08e+12     -0.106      0.915   -4.29e+12    3.85e+12
Region_Central Region              -2.128e+11   1.92e+12     -0.111      0.912   -3.98e+12    3.55e+12
Region_Northeast Region            -2.003e+11   1.86e+12     -0.108      0.914   -3.84e+12    3.44e+12
Region_Southeast Region            -2.212e+11    2.1e+12     -0.105      0.916   -4.34e+12    3.89e+12
Region_Southwest Region            -1.696e+11   1.69e+12     -0.101      0.920   -3.47e+12    3.13e+12
Region_Virginia                     -2.06e+11   1.82e+12     -0.113      0.910   -3.78e+12    3.36e+12
Site_Cleveland                     -7.132e+10    6.6e+11     -0.108      0.914   -1.36e+12    1.22e+12
Site_Connecticut                   -7.132e+10    6.6e+11     -0.108      0.914   -1.36e+12    1.22e+12
Site_Gainesville/Ocala              -5.04e+10   4.14e+11     -0.122      0.903   -8.62e+11    7.61e+11
Site_Greater Louisiana              -5.04e+10   4.14e+11     -0.122      0.903   -8.62e+11    7.61e+11
Site_Hampton Roads                  -6.56e+10   6.99e+11     -0.094      0.925   -1.43e+12     1.3e+12
Site_Kansas/NW Arkansas            -5.882e+10   5.93e+11     -0.099      0.921   -1.22e+12     1.1e+12
Site_Las Vegas                      -1.02e+11   8.33e+11     -0.122      0.903   -1.73e+12    1.53e+12
Site_Macon                          -5.04e+10   4.14e+11     -0.122      0.903   -8.62e+11    7.61e+11
Site_New Orleans                    -5.04e+10   4.14e+11     -0.122      0.903   -8.62e+11    7.61e+11
Site_Northern Virginia              -6.56e+10   6.99e+11     -0.094      0.925   -1.43e+12     1.3e+12
Site_Oklahoma City                 -5.882e+10   5.93e+11     -0.099      0.921   -1.22e+12     1.1e+12
Site_Omaha/Sun Valley              -5.882e+10   5.93e+11     -0.099      0.921   -1.22e+12     1.1e+12
Site_Orange County                 -5.068e+10   4.42e+11     -0.115      0.909   -9.16e+11    8.15e+11
Site_Palos Verdes                  -5.068e+10   4.42e+11     -0.115      0.909   -9.16e+11    8.15e+11
Site_Pensacola                      -5.04e+10   4.14e+11     -0.122      0.903   -8.62e+11    7.61e+11
Site_Phoenix                        -1.02e+11   8.33e+11     -0.122      0.903   -1.73e+12    1.53e+12
Site_Rhode Island                  -7.132e+10    6.6e+11     -0.108      0.914   -1.36e+12    1.22e+12
Site_Roanoke                        -6.56e+10   6.99e+11     -0.094      0.925   -1.43e+12     1.3e+12
Site_San Diego                     -5.068e+10   4.42e+11     -0.115      0.909   -9.16e+11    8.15e+11
Site_Santa Barbara                 -5.068e+10   4.42e+11     -0.115      0.909   -9.16e+11    8.15e+11
Site_Tulsa                         -5.882e+10   5.93e+11     -0.099      0.921   -1.22e+12     1.1e+12
Verified Vendor_N                  -5.974e+11   5.17e+12     -0.116      0.908   -1.07e+13    9.54e+12
Verified Vendor_Y                  -5.974e+11   5.17e+12     -0.116      0.908   -1.07e+13    9.54e+12
Work Order Class_*                    77.1505     74.266      1.039      0.299     -68.410     222.711
Work Order Class_C                    44.3993     74.266      0.598      0.550    -101.160     189.959
Work Order Class_D                    30.3533     74.266      0.409      0.683    -115.207     175.913
Work Order Class_H                     9.8662     74.302      0.133      0.894    -135.764     155.496
Work Order Class_S                    52.4724     74.544      0.704      0.481     -93.632     198.576
Work Order Class_T                    47.1504     74.265      0.635      0.525     -98.408     192.709
Work Order Type_Disconnect          7.292e+11   2.15e+12      0.339      0.735   -3.49e+12    4.95e+12
Work Order Type_Downgrade             2.2e+11   1.93e+12      0.114      0.909   -3.57e+12    4.01e+12
Work Order Type_Install               2.2e+11   1.93e+12      0.114      0.909   -3.57e+12    4.01e+12
Work Order Type_Restart               2.2e+11   1.93e+12      0.114      0.909   -3.57e+12    4.01e+12
Work Order Type_Sro                 7.999e+11   2.35e+12      0.341      0.733    -3.8e+12     5.4e+12
Work Order Type_Trouble Call       -3.708e+12   5.73e+12     -0.648      0.517   -1.49e+13    7.51e+12
Work Order Type_Upgrade               2.2e+11   1.93e+12      0.114      0.909   -3.57e+12    4.01e+12
==============================================================================
Omnibus:                    20933.993   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            42124.342
Skew:                           0.859   Prob(JB):                         0.00
Kurtosis:                       4.925   Cond. No.                     1.68e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.62e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [85]:
regressor = LinearRegression()  
regressor.fit(X_train, y_train) #training the algorithm

print(regressor.intercept_)
print(regressor.coef_)

262360751286715.12
[-2.75074072e+09  1.17481755e+14 -5.11768573e+13 -1.33637362e-01
  4.66352507e+00  1.29428197e+14  6.00169318e+01 -3.30159544e+13
 -3.30159544e+13 -4.41395105e+12 -4.41395105e+12 -4.41395105e+12
 -1.14340993e+14  2.33585588e+13 -1.14340993e+14 -1.44720263e+14
  2.39383486e+13 -1.15155982e+13  9.99781987e+13 -1.42858217e+14
 -2.72385087e+13 -5.36838519e+13  8.40157000e+13 -1.72353542e+13
 -1.72353542e+13 -1.72353542e+13 -1.72353542e+13 -1.72353542e+13
 -1.72353542e+13 -1.72353542e+13 -1.72353542e+13 -1.72353542e+13
 -1.72353542e+13 -1.72353542e+13 -1.72353542e+13 -1.72353542e+13
 -1.72353542e+13 -1.72353542e+13 -1.72353542e+13 -1.72353542e+13
 -1.72353542e+13 -1.72353542e+13 -1.72353542e+13 -9.31515422e+13
 -7.08136328e+13 -1.80841150e+14 -9.02984040e+13  7.60963995e+13
 -5.98180627e+13  6.86655320e+13  6.86655320e+13 -2.18772141e+13
 -2.18772141e+13 -5.23575555e+13 -4.13619853e+13 -1.88272018e+14
 -2.18772141e+13 -2.18772141e+13 -5.23575555e+13 -4.13619853e+13
 -4.13619853e+13 -1.90240759e+13 -1.90240759e+13 -2.18772141e+13
 -1.88272018e+14  6.86655320e+13 -5.23575555e+13 -1.90240759e+13
 -1.90240759e+13 -4.13619853e+13 -5.31438853e+13 -5.31438853e+13
  7.73808594e+01  4.46445312e+01  3.05859375e+01  9.98046875e+00
  5.27380524e+01  4.73320312e+01 -5.32346138e+11 -1.12026143e+14
 -1.12026143e+14 -1.12026143e+14  1.30810273e+14 -1.14237633e+14
 -1.12026143e+14]

In [92]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

        Actual  Predicted
27416    128.0   59.37500
219786    80.0   63.06250
212463     2.0   56.00000
267948   117.0   53.00000
341064     2.0   88.75000
167761    32.0   71.37500
41566      1.0   55.84375
128861   390.0  103.06250
272071    73.0   58.68750
33644     56.0  102.43750
8375      44.0   79.25000
262754   244.0  103.43750
259869    40.0   64.46875
164513   174.0  177.56250
132510     2.0   68.43750
321911     1.0   43.59375
286798   307.0  272.84375
362563   100.0   74.87500
345716   147.0  149.62500
38796     57.0  147.65625
286281    50.0   77.84375
103782   395.0  308.93750
276038    94.0   72.37500
347319   157.0  141.18750
188106    56.0   71.87500
26401     88.0  120.00000
163932   165.0  149.90625
36020    112.0   74.06250
92700     97.0  136.68750
341536     1.0   88.75000
...        ...        ...
24320    134.0   72.31250
96001     67.0   92.06250
49849    149.0   73.37500
315761     1.0   17.62500
65717     98.0   52.00000
59721     16.0   70.81250
29852    100.0  149.12500
141237     1.0  146.56250
250177   105.0  136.62500
161517    66.0   81.21875
242022     2.0   74.93750
41419     98.0   88.75000
89962    317.0  293.09375
172873   141.0  112.43750
177823     8.0   56.00000
175960    65.0   66.75000
190021   359.0  301.96875
46298    320.0   97.00000
87666     35.0   79.37500
272380    97.0  119.15625
243185   299.0  285.84375
355383    45.0  119.09375
26044    380.0  281.90625
135587    54.0   87.56250
234561   324.0  278.31250
244836    45.0  115.12500
333273    12.0   66.12500
363356   377.0  296.56250
363424    37.0   65.31250
198940   305.0  289.78125

[37967 rows x 2 columns]

In [87]:
y_pred = regressor.predict(X_test)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 55.419166644717784
Mean Squared Error: 5447.829535558841
Root Mean Squared Error: 73.809413597175

In [94]:
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(X_train, y_train);

In [95]:
# Use the forest's predict method on the test data
predictions = rf.predict(X_test)
# Calculate the absolute errors
errors = abs(predictions - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'minutes.')

Mean Absolute Error: 51.24 minutes.

In [96]:
nosurvey_time = nosurvey_points * 5
X_train, X_test, y2_train, y2_test = train_test_split(dum_ns_X, nosurvey_time, test_size = 0.2, random_state = 0)

In [97]:
# Calculate the absolute errors
errors = abs(y2_test - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'minutes.')

Mean Absolute Error: 95.49 minutes.